// tslint:disable: no-magic-numbers

/**
 * Binary Prefixes (IEC, 1024-based)
 *
 * @see {@link https://en.wikipedia.org/wiki/Binary_prefix}
 */
export enum BinaryPrefixes {
	/**
	 * Kibi
	 * 1024
	 */
	'Ki' = Math.pow(1024, 1),

	/**
	 * Mibi
	 * 1048576
	 */
	'Mi' = Math.pow(1024, 2),

	/**
	 * Gibi
	 * 1073741824
	 */
	'Gi' = Math.pow(1024, 3),

	/**
	 * Tebi
	 * 1099511627776
	 */
	'Ti' = Math.pow(1024, 4),

	/**
	 * Pebi
	 * 1125899906842624
	 */
	'Pi' = Math.pow(1024, 5),

	/**
	 * Exbi
	 * 1152921504606846976
	 */
	'Ei' = Math.pow(1024, 6),

	/**
	 * Zebi
	 * 1180591620717411303424
	 */
	'Zi' = Math.pow(1024, 7),

	/**
	 * Yobi
	 * 1208925819614629174706176
	 */
	'Yi' = Math.pow(1024, 8),
}

/**
 * Time conversion factors
 */
export enum TimeConversion {
	DAYS_PER_WEEK = 7,
	WEEK_IN_DAYS = DAYS_PER_WEEK,
	HOURS_PER_DAY = 24,
	DAY_IN_HOURS = HOURS_PER_DAY,
	MINUTES_PER_HOUR = 60,
	HOUR_IN_MINUTES = MINUTES_PER_HOUR,
	SECONDS_PER_MINUTE = 60,
	MINUTE_IN_SECONDS = SECONDS_PER_MINUTE,
	MILLISECONDS_PER_SECOND = 1000,
	SECOND_IN_MILLISECONDS = MILLISECONDS_PER_SECOND,
	MICROSECONDS_PER_MILLISECOND = 1000,
	MILLISECOND_IN_MICROSECONDS = MICROSECONDS_PER_MILLISECOND,
	NANOSECONDS_PER_MICROSECOND = 1000,
	MICROSECOND_IN_NANOSECONDS = NANOSECONDS_PER_MICROSECOND,

	HOURS_PER_WEEK = HOURS_PER_DAY * DAYS_PER_WEEK,
	WEEK_IN_HOURS = HOURS_PER_WEEK,

	MINUTES_PER_WEEK = MINUTES_PER_HOUR * HOURS_PER_WEEK,
	WEEK_IN_MINUTES = MINUTES_PER_WEEK,
	MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY,
	DAY_IN_MINUTES = MINUTES_PER_DAY,

	SECONDS_PER_WEEK = SECONDS_PER_MINUTE * MINUTES_PER_WEEK,
	WEEK_IN_SECONDS = SECONDS_PER_WEEK,
	SECONDS_PER_DAY = SECONDS_PER_MINUTE * MINUTES_PER_DAY,
	DAY_IN_SECONDS = SECONDS_PER_DAY,
	SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR,
	HOUR_IN_SECONDS = SECONDS_PER_HOUR,

	MILLISECONDS_PER_WEEK = MILLISECONDS_PER_SECOND * SECONDS_PER_WEEK,
	WEEK_IN_MILLISECONDS = MILLISECONDS_PER_WEEK,
	MILLISECONDS_PER_DAY = MILLISECONDS_PER_SECOND * SECONDS_PER_DAY,
	DAY_IN_MILLISECONDS = MILLISECONDS_PER_DAY,
	MILLISECONDS_PER_HOUR = MILLISECONDS_PER_SECOND * SECONDS_PER_HOUR,
	HOUR_IN_MILLISECONDS = MILLISECONDS_PER_HOUR,
	MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * SECONDS_PER_MINUTE,
	MINUTE_IN_MILLISECONDS = MILLISECONDS_PER_MINUTE,

	MICROSECONDS_PER_WEEK = MICROSECONDS_PER_MILLISECOND * MILLISECONDS_PER_WEEK,
	WEEK_IN_MICROSECONDS = MICROSECONDS_PER_WEEK,
	MICROSECONDS_PER_DAY = MICROSECONDS_PER_MILLISECOND * MILLISECONDS_PER_DAY,
	DAY_IN_MICROSECONDS = MICROSECONDS_PER_DAY,
	MICROSECONDS_PER_HOUR = MICROSECONDS_PER_MILLISECOND * MILLISECONDS_PER_HOUR,
	HOUR_IN_MICROSECONDS = MICROSECONDS_PER_HOUR,
	MICROSECONDS_PER_MINUTE = MICROSECONDS_PER_MILLISECOND *
		MILLISECONDS_PER_MINUTE,
	MINUTE_IN_MICROSECONDS = MICROSECONDS_PER_MINUTE,
	MICROSECONDS_PER_SECOND = MICROSECONDS_PER_MILLISECOND *
		MILLISECONDS_PER_SECOND,
	SECOND_IN_MICROSECONDS = MICROSECONDS_PER_SECOND,

	NANOSECONDS_PER_WEEK = NANOSECONDS_PER_MICROSECOND * MICROSECONDS_PER_WEEK,
	WEEK_IN_NANOSECONDS = NANOSECONDS_PER_WEEK,
	NANOSECONDS_PER_DAY = NANOSECONDS_PER_MICROSECOND * MICROSECONDS_PER_DAY,
	DAY_IN_NANOSECONDS = NANOSECONDS_PER_DAY,
	NANOSECONDS_PER_HOUR = NANOSECONDS_PER_MICROSECOND * MICROSECONDS_PER_HOUR,
	HOUR_IN_NANOSECONDS = NANOSECONDS_PER_HOUR,
	NANOSECONDS_PER_MINUTE = NANOSECONDS_PER_MICROSECOND *
		MICROSECONDS_PER_MINUTE,
	MINUTE_IN_NANOSECONDS = NANOSECONDS_PER_MINUTE,
	NANOSECONDS_PER_SECOND = NANOSECONDS_PER_MICROSECOND *
		MICROSECONDS_PER_SECOND,
	SECOND_IN_NANOSECONDS = NANOSECONDS_PER_SECOND,
	NANOSECONDS_PER_MILLISECOND = NANOSECONDS_PER_MICROSECOND *
		MICROSECONDS_PER_MILLISECOND,
	MILLISECOND_IN_NANOSECONDS = NANOSECONDS_PER_MILLISECOND,
}
